security:
    providers:
        default_user_provider:
            id: Talk2Nextcloud\Security\DefaultUserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            stateless: true
            provider: default_user_provider
            jwt: ~
            custom_authenticators:
                - Talk2Nextcloud\Security\DefaultUserAuthenticator

        main:
            lazy: true

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        - { path: /, roles: PUBLIC_ACCESS }
